# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-21 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SutService', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sut',
            options={'ordering': ('version', 'sutStatus')},
        ),
        migrations.AddField(
            model_name='sut',
            name='sutStatus',
            field=models.CharField(choices=[(b'A', b'Available'), (b'U', b'Unavailable'), (b'F', b'Failed')], default=b'A', max_length=15),
        ),
        migrations.AddField(
            model_name='sut',
            name='version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
