# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-15 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SutService', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tvnf',
        ),
    ]
